feat: make prost-build optional
Since prost v0.11, protoc is no longer bundled and must be installed
on the system, which is not documented in our README.
Make prost-build optional via a feature flag to improve the
initial setup experience for users. Fixes #579

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -57,7 +57,12 @@ jobs:
         uses: ./.github/actions/prepare-build-env
 
       - name: Run cargo build
-        run: cargo build
+        run: |
+          cargo build --features protoc-generated
+          if [ -n "$(git status --porcelain src/generated/vector_tile.rs)" ]; then
+            echo "Error: src/generated/vector_tile.rs is not up to date. Please run `cargo build --features protoc-generated` and commit the changes.";
+            exit 1;
+          fi
 
       - name: Post build environemnt
         if: always()
